# Cargamos datos

In [66]:
import pandas as pd

data = {
    'id_empleado': [101, 102, 103, 104, 105, 105, 106, 107, 108, 109, 110],
    'nombre': [' Ana López ', 'CARLOS GÓMEZ', 'maria rodrigues', 'Juan Pérez', 'Laura Martínez', 'Laura Martínez', '  pedro sánchez ', 'Elena Gomez', None, 'Luis Morales', 'SOFÍA SILVA'],
    'edad': ['28', '35', '42', 'DESCONOCIDO', '31', '31', '-5', '29', '45', 'NaN', '38'],
    'fecha_ingreso': ['2021-01-15', '15/02/2021', '2021/03/10', '2021-04-22', '2021-05-30', '2021-05-30', '2021.06.12', None, '2021-08-01', '2021-09-15', '2021-10-20'],
    'salario': ['$2,500.00', '$3,100.50', '2800', '$4,000.00', '$3,500.00', '$3,500.00', '$1,900.00', '9999999', '$3,200.00', None, '$4,100.00'],
    'departamento': [' Ventas ', 'ventas', '  IT', 'Finanzas', 'IT', 'IT', 'Recursos Humanos', 'ventas', 'Finanzas', '  IT ', 'RECURSOS HUMANOS'],
    'activo': ['Sí', 'SI', 'True', '1', 'No', 'No', '0', 'False', None, 'Sí', 'SI']
}

df = pd.DataFrame(data)

df

,id_empleado,nombre,edad,fecha_ingreso,salario,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,CARLOS GÓMEZ,35,15/02/2021,"$3,100.50",ventas,SI
2,103,maria rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,DESCONOCIDO,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
5,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,pedro sánchez,-5,2021.06.12,"$1,900.00",Recursos Humanos,0
7,107,Elena Gomez,29,NaN,9999999,ventas,False
8,108,NaN,45,2021-08-01,"$3,200.00",Finanzas,NaN
9,109,Luis Morales,NaN,2021-09-15,NaN,IT,Sí
10,110,SOFÍA SILVA,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

### Detectar valores faltantes

In [67]:
df.isna() # Regresa valores True cuando hay celda vacia

df.isna().sum() # Suma de celdas vacias

id_empleado      0
nombre           1
edad             0
fecha_ingreso    1
salario          1
departamento     0
activo           1
dtype: int64

### Eliminar valores vacios

In [68]:
df = df.dropna()

df

,id_empleado,nombre,edad,fecha_ingreso,salario,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,CARLOS GÓMEZ,35,15/02/2021,"$3,100.50",ventas,SI
2,103,maria rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,DESCONOCIDO,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
5,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,pedro sánchez,-5,2021.06.12,"$1,900.00",Recursos Humanos,0
10,110,SOFÍA SILVA,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

### Contar duplicados

In [69]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
10    False
dtype: bool

### Eliminar duplicados

In [70]:
df = df.drop_duplicates()

df

,id_empleado,nombre,edad,fecha_ingreso,salario,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,CARLOS GÓMEZ,35,15/02/2021,"$3,100.50",ventas,SI
2,103,maria rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,DESCONOCIDO,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,pedro sánchez,-5,2021.06.12,"$1,900.00",Recursos Humanos,0
10,110,SOFÍA SILVA,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

### Cambiar tipos de columnas

In [71]:
df["id_empleado"] = df["id_empleado"].astype("string")

df["id_empleado"]

0     101
1     102
2     103
3     104
4     105
6     106
10    110
Name: id_empleado, dtype: string

### Rellenar celdas vacias

In [72]:
df["edad"] = pd.to_numeric(df["edad"], errors="coerce") # Convertir a none si no puede convertir a numeric

df.loc[df["edad"] <= 0, "edad"] = None # Cambiar a none edades negativas

df["edad"] = df["edad"].fillna(
    df["edad"].median()
)

df["edad"] = df["edad"].astype(int) # Regresamos a entero
df

,id_empleado,nombre,edad,fecha_ingreso,salario,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,CARLOS GÓMEZ,35,15/02/2021,"$3,100.50",ventas,SI
2,103,maria rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,35,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,pedro sánchez,35,2021.06.12,"$1,900.00",Recursos Humanos,0
10,110,SOFÍA SILVA,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

## Renombrar columnas

In [73]:
df = df.rename(columns={"salario":"salario esperado"})
df

,id_empleado,nombre,edad,fecha_ingreso,salario esperado,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,CARLOS GÓMEZ,35,15/02/2021,"$3,100.50",ventas,SI
2,103,maria rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,35,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,pedro sánchez,35,2021.06.12,"$1,900.00",Recursos Humanos,0
10,110,SOFÍA SILVA,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

## Limpiar textos

In [74]:
df["nombre"] = df["nombre"].str.strip()
df["nombre"] = df["nombre"].str.lower()
df["nombre"] = df["nombre"].str.title()

df

,id_empleado,nombre,edad,fecha_ingreso,salario esperado,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Sí
1,102,Carlos Gómez,35,15/02/2021,"$3,100.50",ventas,SI
2,103,Maria Rodrigues,42,2021/03/10,2800,IT,True
3,104,Juan Pérez,35,2021-04-22,"$4,000.00",Finanzas,1
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,No
6,106,Pedro Sánchez,35,2021.06.12,"$1,900.00",Recursos Humanos,0
10,110,Sofía Silva,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,SI

## Reemplazar celdas

In [75]:
mapeo = {
    "si": "Activo",
    "true": "Activo",
    "1": "Activo",
    "1.0": "Activo",  # Por si hay flotantes
    "no": "Inactivo",
    "false": "Inactivo",
    "0": "Inactivo",
    "0.0": "Inactivo",
}

df["activo"] = (
    df["activo"]
    .astype(str)
    .str.normalize("NFKD") # Normalizar para separar las palabras y los acentos b"S´i"
    .str.encode("ascii", errors="ignore") # Borra los caracteres especiales que pasa cuando se separan los acentos b"Si"
    .str.decode("utf-8") # Vuelve a transformar el texto en string "Si"
    .str.lower()
    .str.strip()
)

df["activo"] = df["activo"].replace(mapeo)
df

,id_empleado,nombre,edad,fecha_ingreso,salario esperado,departamento,activo
0,101,Ana López,28,2021-01-15,"$2,500.00",Ventas,Activo
1,102,Carlos Gómez,35,15/02/2021,"$3,100.50",ventas,Activo
2,103,Maria Rodrigues,42,2021/03/10,2800,IT,Activo
3,104,Juan Pérez,35,2021-04-22,"$4,000.00",Finanzas,Activo
4,105,Laura Martínez,31,2021-05-30,"$3,500.00",IT,Inactivo
6,106,Pedro Sánchez,35,2021.06.12,"$1,900.00",Recursos Humanos,Inactivo
10,110,Sofía Silva,38,2021-10-20,"$4,100.00",RECURSOS HUMANOS,Activo

###