## Group by

Se utiliza para agrupar filas que tienen valores en común y realiza operaciones sobre cada grupo, como sumas, promedios, conteos o estadisticas
1. Divide los datos en grupos
2. Aplica una operación a cada grupo
3. Combina los resultados en una nueva estructura

In [2]:
import pandas as pd

data = {
    "vendedor": ["Ana", "Luis", "Marta", "Pedro", "Sofia",
                 "Diego", "Laura", "Carlos", "Elena", "Ivan"],
    "sucursal": ["Norte", "Norte", "Sur", "Sur", "Norte",
                 "Sur", "Norte", "Sur", "Norte", "Sur"],
    "producto": ["Laptop", "Mouse", "Laptop", "Mouse", "Laptop",
                 "Laptop", "Mouse", "Mouse", "Laptop", "Mouse"],
    "ventas": [15000, 1000, 14000, 1200, 16000,
               15500, 900, 1100, 17000, 1300],
    "unidades": [3, 10, 2, 12, 3, 3, 9, 11, 4, 13]
}

df = pd.DataFrame(data)
df

  vendedor sucursal producto  ventas  unidades
0      Ana    Norte   Laptop   15000         3
1     Luis    Norte    Mouse    1000        10
2    Marta      Sur   Laptop   14000         2
3    Pedro      Sur    Mouse    1200        12
4    Sofia    Norte   Laptop   16000         3
5    Diego      Sur   Laptop   15500         3
6    Laura    Norte    Mouse     900         9
7   Carlos      Sur    Mouse    1100        11
8    Elena    Norte   Laptop   17000         4
9     Ivan      Sur    Mouse    1300        13

### Agrupación 1 columna

In [3]:
df.groupby("sucursal")["ventas"].sum()

sucursal
Norte    49900
Sur      33100
Name: ventas, dtype: int64

### Agrupación mas columnas

In [4]:
df.groupby("sucursal")[["ventas", "unidades"]].sum()

          ventas  unidades
sucursal
Norte      49900        29
Sur        33100        41

## Agrupación multiples columnas

In [5]:
df.groupby(["sucursal", "producto"])["ventas"].sum()

df.groupby(
    ["sucursal", "producto"],
    as_index=False
)["ventas"].sum() # as_index conserva las columnas utilizadas para agrupar como columnas normales

  sucursal producto  ventas
0    Norte   Laptop   48000
1    Norte    Mouse    1900
2      Sur   Laptop   29500
3      Sur    Mouse    3600

---

## Funciones de agregación mas utilizadas

In [6]:
# Promedio de ventas por sucursal
df.groupby("sucursal")["ventas"].mean()

# Venta máxima por sucursal
df.groupby("sucursal")["ventas"].max()

# Venta mínima por sucursal
df.groupby("sucursal")["ventas"].min()

# Número de registros por sucursal
df.groupby("sucursal").size()

# Cantidad de productos diferentes por sucursal
df.groupby("sucursal")["producto"].nunique()

df["producto"].value_counts()
# sum(), count(), median(), std()

producto
Laptop    5
Mouse     5
Name: count, dtype: int64

---

## agg()

Permite aplicar diferentes operaciones en una sola agrupación

In [7]:
df.groupby("sucursal")["ventas"].agg([
    "sum",
    "mean",
    "max",
    "min",
    "count"
])

            sum    mean    max   min  count
sucursal
Norte     49900  9980.0  17000   900      5
Sur       33100  6620.0  15500  1100      5

Tambien se puede aplicar operaciones distintas a diferentes columnas

In [8]:
df.groupby("sucursal").agg({
    "ventas": ["sum", "mean", "max"],
    "unidades": ["sum", "mean"]
})

         ventas                unidades
            sum    mean    max      sum mean
sucursal
Norte     49900  9980.0  17000       29  5.8
Sur       33100  6620.0  15500       41  8.2

---

## transform()

Devuelve un valor por cada fila original, en vez de resumir cada grupo en una sola fila

In [9]:
df["promedio_sucursal"] = (
    df.groupby("sucursal")["ventas"].transform("mean")
)

df

  vendedor sucursal producto  ventas  unidades  promedio_sucursal
0      Ana    Norte   Laptop   15000         3             9980.0
1     Luis    Norte    Mouse    1000        10             9980.0
2    Marta      Sur   Laptop   14000         2             6620.0
3    Pedro      Sur    Mouse    1200        12             6620.0
4    Sofia    Norte   Laptop   16000         3             9980.0
5    Diego      Sur   Laptop   15500         3             6620.0
6    Laura    Norte    Mouse     900         9             9980.0
7   Carlos      Sur    Mouse    1100        11             6620.0
8    Elena    Norte   Laptop   17000         4             9980.0
9     Ivan      Sur    Mouse    1300        13             6620.0

In [10]:
df["diferencia_promedio"] = (
    df["ventas"] - df["promedio_sucursal"]
)

df

,vendedor,sucursal,producto,ventas,unidades,promedio_sucursal,diferencia_promedio
0,Ana,Norte,Laptop,15000,3,9980.0,5020.0
1,Luis,Norte,Mouse,1000,10,9980.0,-8980.0
2,Marta,Sur,Laptop,14000,2,6620.0,7380.0
3,Pedro,Sur,Mouse,1200,12,6620.0,-5420.0
4,Sofia,Norte,Laptop,16000,3,9980.0,6020.0
5,Diego,Sur,Laptop,15500,3,6620.0,8880.0
6,Laura,Norte,Mouse,900,9,9980.0,-9080.0
7,Carlos,Sur,Mouse,1100,11,6620.0,-5520.0
8,Elena,Norte,Laptop,17000,4,9980.0,7020.0
9,Ivan,Sur,Mouse,1300,13,6620.0,-5320.0

---

## filter()

Evalua la condición sobre todos el grupo y conserva o elimina sus fila

In [11]:
df.groupby("sucursal").filter(
    lambda grupo: grupo["ventas"].sum() > 40000
)
df

,vendedor,sucursal,producto,ventas,unidades,promedio_sucursal,diferencia_promedio
0,Ana,Norte,Laptop,15000,3,9980.0,5020.0
1,Luis,Norte,Mouse,1000,10,9980.0,-8980.0
2,Marta,Sur,Laptop,14000,2,6620.0,7380.0
3,Pedro,Sur,Mouse,1200,12,6620.0,-5420.0
4,Sofia,Norte,Laptop,16000,3,9980.0,6020.0
5,Diego,Sur,Laptop,15500,3,6620.0,8880.0
6,Laura,Norte,Mouse,900,9,9980.0,-9080.0
7,Carlos,Sur,Mouse,1100,11,6620.0,-5520.0
8,Elena,Norte,Laptop,17000,4,9980.0,7020.0
9,Ivan,Sur,Mouse,1300,13,6620.0,-5320.0

---

## Ordenar despues de agrupar

In [12]:
ventas_producto = (
    df.groupby("producto", as_index=False)["ventas"]
    .sum()
    .sort_values("ventas", ascending=False)
)

ventas_producto

  producto  ventas
0   Laptop   77500
1    Mouse    5500