# Transformaciones

Permiten modificar, convertir o crear información a partir de las columnas de un dataframe

axis=0 - Index o Renglones


axis=1 - Columnas

## Crear dataframe

In [12]:
import pandas as pd
import numpy as np

data = {
    "producto": [" Laptop ", "mouse", "TECLADO", "Monitor", "Mouse", " Laptop "],
    "categoria": ["Tecnologia", "Accesorios", "Accesorios",
                  "Tecnologia", "Accesorios", "Tecnologia"],
    "precio": [15000, 300, 800, 4000, 300, 15500],
    "cantidad": [2, 5, 3, 1, 4, 1],
    "descuento": [0.10, 0, 0.05, 0.15, 0, 0.10],
    "fecha": ["2026-01-10", "2026-01-11", "2026-01-11",
              "2026-02-05", "2026-02-06", "2026-02-07"]
}

df = pd.DataFrame(data)
df

   producto   categoria  precio  cantidad  descuento       fecha
0   Laptop   Tecnologia   15000         2       0.10  2026-01-10
1     mouse  Accesorios     300         5       0.00  2026-01-11
2   TECLADO  Accesorios     800         3       0.05  2026-01-11
3   Monitor  Tecnologia    4000         1       0.15  2026-02-05
4     Mouse  Accesorios     300         4       0.00  2026-02-06
5   Laptop   Tecnologia   15500         1       0.10  2026-02-07

## Operaciones vectorizadas

In [13]:
df["subtotal"] = df["precio"] * df["cantidad"]
df["precio_doble"] = df["precio"] * 2

df["total"] = df["subtotal"] * (1 - df["descuento"])

df[["producto", "precio", "cantidad", "descuento", "subtotal", "total"]]

   producto  precio  cantidad  descuento  subtotal    total
0   Laptop    15000         2       0.10     30000  27000.0
1     mouse     300         5       0.00      1500   1500.0
2   TECLADO     800         3       0.05      2400   2280.0
3   Monitor    4000         1       0.15      4000   3400.0
4     Mouse     300         4       0.00      1200   1200.0
5   Laptop    15500         1       0.10     15500  13950.0

---

## map()
Aplica una correspondencia o función a cada elemento de una Serie

In [14]:
# Usando diccionario

categorias = {
    "Tecnologia": 1,
    "Accesorios": 2
}

df["categoria_codigo"] = df["categoria"].map(categorias)

df

,producto,categoria,precio,cantidad,descuento,fecha,subtotal,precio_doble,total,categoria_codigo
0,Laptop,Tecnologia,15000,2,0.10,2026-01-10,30000,30000,27000.0,1
1,mouse,Accesorios,300,5,0.00,2026-01-11,1500,600,1500.0,2
2,TECLADO,Accesorios,800,3,0.05,2026-01-11,2400,1600,2280.0,2
3,Monitor,Tecnologia,4000,1,0.15,2026-02-05,4000,8000,3400.0,1
4,Mouse,Accesorios,300,4,0.00,2026-02-06,1200,600,1200.0,2
5,Laptop,Tecnologia,15500,1,0.10,2026-02-07,15500,31000,13950.0,1

In [15]:
# Usa funcion lambda
df["precio_usd"] = df["precio"].map(lambda x: x / 18)

df

,producto,categoria,precio,cantidad,descuento,fecha,subtotal,precio_doble,total,categoria_codigo,precio_usd
0,Laptop,Tecnologia,15000,2,0.10,2026-01-10,30000,30000,27000.0,1,833.333333
1,mouse,Accesorios,300,5,0.00,2026-01-11,1500,600,1500.0,2,16.666667
2,TECLADO,Accesorios,800,3,0.05,2026-01-11,2400,1600,2280.0,2,44.444444
3,Monitor,Tecnologia,4000,1,0.15,2026-02-05,4000,8000,3400.0,1,222.222222
4,Mouse,Accesorios,300,4,0.00,2026-02-06,1200,600,1200.0,2,16.666667
5,Laptop,Tecnologia,15500,1,0.10,2026-02-07,15500,31000,13950.0,1,861.111111

---

## apply()

Permite ejecutar funciones sobre una Serie o sobre las filas y columnas de un Dataframe

In [16]:
def clasificar_precio(precio):
    if precio >= 5000:
        return "Alto"
    return "Bajo"

df["tipo_precio"] = df["precio"].apply(clasificar_precio)

df

,producto,categoria,precio,cantidad,descuento,fecha,subtotal,precio_doble,total,categoria_codigo,precio_usd,tipo_precio
0,Laptop,Tecnologia,15000,2,0.10,2026-01-10,30000,30000,27000.0,1,833.333333,Alto
1,mouse,Accesorios,300,5,0.00,2026-01-11,1500,600,1500.0,2,16.666667,Bajo
2,TECLADO,Accesorios,800,3,0.05,2026-01-11,2400,1600,2280.0,2,44.444444,Bajo
3,Monitor,Tecnologia,4000,1,0.15,2026-02-05,4000,8000,3400.0,1,222.222222,Bajo
4,Mouse,Accesorios,300,4,0.00,2026-02-06,1200,600,1200.0,2,16.666667,Bajo
5,Laptop,Tecnologia,15500,1,0.10,2026-02-07,15500,31000,13950.0,1,861.111111,Alto

In [17]:
def clasificar_venta(fila):
    if fila["precio"] > 5000 and fila["cantidad"] >= 2:
        return "Importante"
    return "Normal"

df["tipo_venta"] = df.apply(clasificar_venta, axis=1)

df

,producto,categoria,precio,cantidad,descuento,fecha,subtotal,precio_doble,total,categoria_codigo,precio_usd,tipo_precio,tipo_venta
0,Laptop,Tecnologia,15000,2,0.10,2026-01-10,30000,30000,27000.0,1,833.333333,Alto,Importante
1,mouse,Accesorios,300,5,0.00,2026-01-11,1500,600,1500.0,2,16.666667,Bajo,Normal
2,TECLADO,Accesorios,800,3,0.05,2026-01-11,2400,1600,2280.0,2,44.444444,Bajo,Normal
3,Monitor,Tecnologia,4000,1,0.15,2026-02-05,4000,8000,3400.0,1,222.222222,Bajo,Normal
4,Mouse,Accesorios,300,4,0.00,2026-02-06,1200,600,1200.0,2,16.666667,Bajo,Normal
5,Laptop,Tecnologia,15500,1,0.10,2026-02-07,15500,31000,13950.0,1,861.111111,Alto,Normal

---

## replace()

Permite sustituir valores especificos, manteniendo los demas sin modificaciones

In [18]:
df["categoria_ingles"] = df["categoria"].replace({
    "Tecnologia": "Tech",
    "Accesorios": "Accessories"
})

df[["categoria", "categoria_ingles"]]

    categoria categoria_ingles
0  Tecnologia             Tech
1  Accesorios      Accessories
2  Accesorios      Accessories
3  Tecnologia             Tech
4  Accesorios      Accessories
5  Tecnologia             Tech

---

### Comparación entre map(), apply() y replace()

- map(): Transformar valores individualmente mediante un diccionario o función (Series)
- replace(): Sustituir valores especificos por otros (Series o DF)
- apply(): Ejecutar funciones personalizadas (Series o DF)


---

## np.where() y np.select()
Permite asignar valores dependiendo de una condición

In [19]:
# Dos resultados posibles
df["venta_especial"] = np.where(
    (df["precio"] > 5000) & (df["cantidad"] >= 2),
    "Si",
    "No"
)

# Varias condiciones: se utiliza la primera que se cumpla
condiciones = [
    df["total"] >= 20000,
    df["total"] >= 5000
]

df["clasificacion"] = np.select(
    condiciones,
    ["Alta", "Media"],
    default="Baja"
)

df[["producto", "total", "venta_especial", "clasificacion"]]

   producto    total venta_especial clasificacion
0   Laptop   27000.0             Si          Alta
1     mouse   1500.0             No          Baja
2   TECLADO   2280.0             No          Baja
3   Monitor   3400.0             No          Baja
4     Mouse   1200.0             No          Baja
5   Laptop   13950.0             No         Media

## pd.cut()

Permite convertir valores numéricos en intervalos o grupos

In [20]:
df["rango_precio"] = pd.cut(
    df["precio"],
    bins=[0, 1000, 5000, float("inf")], # 1 - 1000 Economico, 1001 - 5000 Medio, 5001+ Caro 
    labels=["Economico", "Medio", "Caro"]
)

df[["producto", "precio", "rango_precio"]]

   producto  precio rango_precio
0   Laptop    15000         Caro
1     mouse     300    Economico
2   TECLADO     800    Economico
3   Monitor    4000        Medio
4     Mouse     300    Economico
5   Laptop    15500         Caro

## assign()

Crear columnas sin modificar directamente el DataFrame

In [21]:
nuevo_df = df.assign(
    impuesto=lambda x: x["subtotal"] * 0.16,
    total_con_impuesto=lambda x: x["subtotal"] * 1.16
)
nuevo_df

,producto,categoria,precio,cantidad,descuento,fecha,subtotal,precio_doble,total,categoria_codigo,precio_usd,tipo_precio,tipo_venta,categoria_ingles,venta_especial,clasificacion,rango_precio,impuesto,total_con_impuesto
0,Laptop,Tecnologia,15000,2,0.10,2026-01-10,30000,30000,27000.0,1,833.333333,Alto,Importante,Tech,Si,Alta,Caro,4800.0,34800.0
1,mouse,Accesorios,300,5,0.00,2026-01-11,1500,600,1500.0,2,16.666667,Bajo,Normal,Accessories,No,Baja,Economico,240.0,1740.0
2,TECLADO,Accesorios,800,3,0.05,2026-01-11,2400,1600,2280.0,2,44.444444,Bajo,Normal,Accessories,No,Baja,Economico,384.0,2784.0
3,Monitor,Tecnologia,4000,1,0.15,2026-02-05,4000,8000,3400.0,1,222.222222,Bajo,Normal,Tech,No,Baja,Medio,640.0,4640.0
4,Mouse,Accesorios,300,4,0.00,2026-02-06,1200,600,1200.0,2,16.666667,Bajo,Normal,Accessories,No,Baja,Economico,192.0,1392.0
5,Laptop,Tecnologia,15500,1,0.10,2026-02-07,15500,31000,13950.0,1,861.111111,Alto,Normal,Tech,No,Media,Caro,2480.0,17980.0

---

## transform()

Transformar manteniendo las filas

In [22]:
df["promedio_categoria"] = (
    df.groupby("categoria")["total"]
      .transform("mean")
)

df[["producto", "categoria", "total", "promedio_categoria"]]

   producto   categoria    total  promedio_categoria
0   Laptop   Tecnologia  27000.0        14783.333333
1     mouse  Accesorios   1500.0         1660.000000
2   TECLADO  Accesorios   2280.0         1660.000000
3   Monitor  Tecnologia   3400.0        14783.333333
4     Mouse  Accesorios   1200.0         1660.000000
5   Laptop   Tecnologia  13950.0        14783.333333

---

## One Hot Vector

In [ ]:
#pd.get_dummies() - Categorizar un valor en un rango de rangos con 1 si entra o 0 si no