# merge(), join() y concat()

En Pandas, combinar DataFrames es una operación fundamental para trabajar con información almacenada en diferentes tablas como clientes, ventas, productos o empleados

- merge(): Sirve para combinar DF utilizando columnas en comun 
- join(): Combinar DF mediante sus indices
- concat(): Unir DF vertical u horizontalmente

---

## Crear DF

In [4]:
import pandas as pd

clientes = pd.DataFrame({
    "id_cliente": [1, 2, 3, 4],
    "nombre": ["Ana", "Luis", "Marta", "Sofia"],
    "ciudad": ["Aguascalientes", "Leon", "Zacatecas", "Aguascalientes"]
})

ventas = pd.DataFrame({
    "id_venta": [101, 102, 103, 104],
    "id_cliente": [1, 2, 1, 5],
    "monto": [1500, 500, 800, 1200]
})

---

## pd.merge()

In [ ]:
'''
pd.merge(
    dataframe_izquierdo,
    dataframe_derecho,
    on="columna_comun",
    how="inner"
    (Opcional) right_on= Nombre de la columna 
    (Opcional) left_on= Nombre de la columna
    (Opcional) suffixes = (_sufijo de columna repetida t1, _sufino de columna repetida t2)
    (Opcional) indicator = True | False, mostrar de donde vienen los registros
    (Opcional) validate="one_to_one" | "one_to_many ... verificar las relaciones entre las tablas
)
'''

'\npd.merge(\n    dataframe_izquierdo,\n    dataframe_derecho,\n    on="columna_comun",\n    how="inner"\n)\n'

### Inner

Conserva filas cuya clave existe en ambos df

In [8]:
resultado = pd.merge(
    clientes,
    ventas,
    on="id_cliente",
    how="inner"
)

resultado

   id_cliente nombre          ciudad  id_venta  monto
0           1    Ana  Aguascalientes       101   1500
1           1    Ana  Aguascalientes       103    800
2           2   Luis            Leon       102    500

### left
Conserva todo lo de la izquierda independiente si tiene lo de la derecha

In [9]:
resultado = pd.merge(
    clientes,
    ventas,
    on="id_cliente",
    how="left"
)

resultado

   id_cliente nombre          ciudad  id_venta   monto
0           1    Ana  Aguascalientes     101.0  1500.0
1           1    Ana  Aguascalientes     103.0   800.0
2           2   Luis            Leon     102.0   500.0
3           3  Marta       Zacatecas       NaN     NaN
4           4  Sofia  Aguascalientes       NaN     NaN

### right

Conserva todo derecha independientemente de izquierda

In [10]:
resultado = pd.merge(
    clientes,
    ventas,
    on="id_cliente",
    how="right"
)

resultado

   id_cliente nombre          ciudad  id_venta  monto
0           1    Ana  Aguascalientes       101   1500
1           2   Luis            Leon       102    500
2           1    Ana  Aguascalientes       103    800
3           5    NaN             NaN       104   1200

### Outer
Incluye todo

In [11]:
resultado = pd.merge(
    clientes,
    ventas,
    on="id_cliente",
    how="outer"
)

resultado

   id_cliente nombre          ciudad  id_venta   monto
0           1    Ana  Aguascalientes     101.0  1500.0
1           1    Ana  Aguascalientes     103.0   800.0
2           2   Luis            Leon     102.0   500.0
3           3  Marta       Zacatecas       NaN     NaN
4           4  Sofia  Aguascalientes       NaN     NaN
5           5    NaN             NaN     104.0  1200.0

---

## join()

Alternativa a merge() cuando los datos están relacionados por sus indices

In [12]:
clientes_idx = clientes.set_index("id_cliente")
ventas_idx = ventas.set_index("id_cliente")

resultado = clientes_idx.join(
    ventas_idx,
    how="left"
)

resultado

           nombre          ciudad  id_venta   monto
id_cliente
1             Ana  Aguascalientes     101.0  1500.0
1             Ana  Aguascalientes     103.0   800.0
2            Luis            Leon     102.0   500.0
3           Marta       Zacatecas       NaN     NaN
4           Sofia  Aguascalientes       NaN     NaN

---

## pd.concat()

Simplemente concatena DF a lo largo de un eje

### Unir verticalmente (axis = 0)

In [13]:
enero = pd.DataFrame({
    "producto": ["Laptop", "Mouse"],
    "ventas": [15000, 500]
})

febrero = pd.DataFrame({
    "producto": ["Monitor", "Teclado"],
    "ventas": [4000, 800]
})

resultado = pd.concat(
    [enero, febrero],
    ignore_index=True
)

resultado

  producto  ventas
0   Laptop   15000
1    Mouse     500
2  Monitor    4000
3  Teclado     800

### Unir horizontalmente (axis = 1)

In [14]:
datos = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta"]
})

calificaciones = pd.DataFrame({
    "calificacion": [95, 88, 92]
})

resultado = pd.concat(
    [datos, calificaciones],
    axis=1
)

resultado

  nombre  calificacion
0    Ana            95
1   Luis            88
2  Marta            92