# Exploratory Data Analysis

Proceso de examinar un dataset para comprender su estructura, identificar patrones, detectar problemas de calidad y descubrir relaciones entre variables.


---

## Crear DF

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "id_venta": [101, 102, 103, 104, 105, 106,
                 107, 108, 109, 110, 111, 112],
    "fecha": [
        "2026-01-03", "2026-01-05", "2026-01-06",
        "2026-01-12", "2026-01-19", "2026-01-20",
        "2026-02-01", "2026-02-04", "2026-02-09",
        "2026-02-12", "2026-02-15", "2026-02-20"
    ],
    "sucursal": [
        "Norte", "Sur", "Norte", "Centro",
        "Sur", "Centro", "Norte", "Sur",
        "Centro", "Norte", "Sur", "Centro"
    ],
    "producto": [
        "Laptop", "Mouse", "Teclado", "Monitor",
        "Laptop", "Mouse", "Laptop", "Monitor",
        "Teclado", "Mouse", "Laptop", "Monitor"
    ],
    "precio": [
        15000, 350, 850, 4500, 14500, 320,
        15800, 4800, 900, 300, 14900, 4400
    ],
    "unidades": [1, 4, 2, 1, 2, 5, 1, 1, 3, 4, 1, 2],
    "satisfaccion": [
        5, 4, 4, 5, 5, 3,
        5, np.nan, 4, 3, 5, 4
    ]
}

df = pd.DataFrame(data)

# Agregamos un duplicado intencional para practicar
df = pd.concat([df, df.iloc[[-1]]], ignore_index=True)

df

    id_venta       fecha sucursal producto  precio  unidades  satisfaccion
0        101  2026-01-03    Norte   Laptop   15000         1           5.0
1        102  2026-01-05      Sur    Mouse     350         4           4.0
2        103  2026-01-06    Norte  Teclado     850         2           4.0
3        104  2026-01-12   Centro  Monitor    4500         1           5.0
4        105  2026-01-19      Sur   Laptop   14500         2           5.0
5        106  2026-01-20   Centro    Mouse     320         5           3.0
6        107  2026-02-01    Norte   Laptop   15800         1           5.0
7        108  2026-02-04      Sur  Monitor    4800         1           NaN
8        109  2026-02-09   Centro  Teclado     900         3           4.0
9        110  2026-02-12    Norte    Mouse     300         4           3.0
10       111  2026-02-15      Sur   Laptop   14900         1           5.0
11       112  2026-02-20   Centro  Monitor    4400         2           4.0
12       112  2026-02-20   Centro  Monitor    4400         2           4.0

## head() y tail()

In [9]:
# Primeras cinco filas
df.head()

# Últimas cinco filas
df.tail()

# Primeras diez filas
df.head(10)

   id_venta       fecha sucursal producto  precio  unidades  satisfaccion
0       101  2026-01-03    Norte   Laptop   15000         1           5.0
1       102  2026-01-05      Sur    Mouse     350         4           4.0
2       103  2026-01-06    Norte  Teclado     850         2           4.0
3       104  2026-01-12   Centro  Monitor    4500         1           5.0
4       105  2026-01-19      Sur   Laptop   14500         2           5.0
5       106  2026-01-20   Centro    Mouse     320         5           3.0
6       107  2026-02-01    Norte   Laptop   15800         1           5.0
7       108  2026-02-04      Sur  Monitor    4800         1           NaN
8       109  2026-02-09   Centro  Teclado     900         3           4.0
9       110  2026-02-12    Norte    Mouse     300         4           3.0

## shape, columns y dtypes

In [10]:
# Dimensiones: (filas, columnas)
df.shape

# Nombres de las columnas
df.columns

# Tipos de datos
df.dtypes

id_venta          int64
fecha               str
sucursal            str
producto            str
precio            int64
unidades          int64
satisfaccion    float64
dtype: object

## info()

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_venta      13 non-null     int64
 1   fecha         13 non-null     str
 2   sucursal      13 non-null     str
 3   producto      13 non-null     str
 4   precio        13 non-null     int64
 5   unidades      13 non-null     int64
 6   satisfaccion  12 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 860.0 bytes

## describe()

In [12]:
df.describe()

         id_venta        precio   unidades  satisfaccion
count   13.000000     13.000000  13.000000     12.000000
mean   106.923077   6232.307692   2.230769      4.250000
std      3.774068   6362.755108   1.363442      0.753778
min    101.000000    300.000000   1.000000      3.000000
25%    104.000000    850.000000   1.000000      4.000000
50%    107.000000   4400.000000   2.000000      4.000000
75%    110.000000  14500.000000   3.000000      5.000000
max    112.000000  15800.000000   5.000000      5.000000

In [13]:
df.describe(include="object")

C:\Users\david\AppData\Local\Temp\ipykernel_39616\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

             fecha sucursal producto
count           13       13       13
unique          12        3        4
top     2026-02-20   Centro   Laptop
freq             2        5        4

### Estadisticas individuales

In [14]:
df["precio"].mean()       # Promedio
df["precio"].median()     # Mediana
df["precio"].mode()       # Moda
df["precio"].std()        # Desviación estándar
df["precio"].min()        # Mínimo
df["precio"].max()        # Máximo
df["precio"].quantile(.25) # Primer cuartil

np.float64(850.0)

## Pivot table
Tablas dinamicas de Excel

In [16]:
df["total"] = df["precio"] * df["unidades"]

tabla = pd.pivot_table(
    df,
    values="total",
    index="sucursal",
    columns="producto",
    aggfunc="sum",
    fill_value=0
)

tabla

producto  Laptop  Monitor  Mouse  Teclado
sucursal
Centro         0    22100   1600     2700
Norte      30800        0   1200     1700
Sur        43900     4800   1400        0

## corr()
Mide la intensidad y dirección de la relación lineal entre dos variables numéricas

Usa Pearson:
- 1: positiva fuerte
- -1: negativa fuerte
- 0: debil o inexistente

In [17]:
df[["precio", "unidades", "total"]].corr()

            precio  unidades     total
precio    1.000000 -0.677569  0.882596
unidades -0.677569  1.000000 -0.501458
total     0.882596 -0.501458  1.000000

## nlargest() / nsmallest()

In [18]:
# Las 3 ventas con mayores ingresos
df.nlargest(3, "total")

# Las 3 ventas con menores ingresos
df.nsmallest(3, "total")

,id_venta,fecha,sucursal,producto,precio,unidades,satisfaccion,total
9,110,2026-02-12,Norte,Mouse,300,4,3.0,1200
1,102,2026-01-05,Sur,Mouse,350,4,4.0,1400
5,106,2026-01-20,Centro,Mouse,320,5,3.0,1600